name: production
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install Dependencies
        run: npm ci
      - name: Lint & Build & Export
        run: npm run export
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: out
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: out
          path: out
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
